### ISSUE TITLE
Moderate Severity: Axios CSRF Vulnerability in Versions 0.8.1 to 1.5.1

### ISSUE THREAD

**Issue by fundWJ** [cloudconvert/cloudconvert-node#111]
Hi,

We recently found this issue when updating the packages,
in `npm audit` we got this Moderate Severity issue:

current cloudconvert version: 2.3.5
```
axios  0.8.1 - 1.5.1
Severity: moderate
Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx
fix available via `npm audit fix --force`
node_modules/cloudconvert/node_modules/axios
  cloudconvert  >=2.0.0
  Depends on vulnerable versions of axios
  node_modules/cloudconvert
```

Would be great if this can be updated.
Thank you.

**Comment by nikos-pblworks** [comment]
+1

**Comment by josiasmontag** [comment]
This vulnerability does not affect the SDK because we don't use axios with XSRF-TOKEN cookies or any external hosts.

Nevertheless, we should update the SDK dependencies in general.
@KnorpelSenf would be great if you had a minute for this.

**Comment by stefansundin** [comment]
It would also be great if there could be a new major version that uses the built-in Node.js fetch support which has been stable since Node.js v18.

The `form-data` package could also be removed since there's built-in FormData in Node.js since v18 as well.

I think removing them is the best option security wise, and I don't see much reason to continue supporting Node.js versions less than v18.

**Comment by KnorpelSenf** [comment]
Sure thing, I'll tackle this.

> The `form-data` package could also be removed since there's built-in FormData in Node.js since v18 as well.

We need to be able to stream data. The `form-data` package provides a way to `.append` most streams and have it work automatically. Unfortunately, the web specs for `FormData` as implemented in Node.js force you to buffer the entire file in memory before sending it. (Who thought that this was a good idea???)

IMO we have two options:
- keep on using `form-data`
- drop down to constructing a multipart/form-data stream (I [did this](https://github.com/grammyjs/grammY/blob/bd67f5b1d0ff74147c092fc659e1ef980aa8fd28/src/core/payload.ts#L106) once)

@stefansundin is there another way to go about this?

**Comment by KnorpelSenf** [comment]
Check out the work-in-progress pull request for this at #112.

I am happy to drop axios and bump to Node 16 in order to use `fetch`. I have two more questions about this:
1. Should we directly go higher? Node 16 is not even maintained anymore (https://nodejs.org/en/about/previous-releases) so perhaps we should directly require version 18? Downside: breaking change for more people than needed.
2. The WIP currently does not compile because apparently `form-data` has no proper integration with web fetch. Dependig on what we want to do with `form-data`, how should we continue with this?

**Comment by josiasmontag** [comment]
We can directly go with Node 18 and drop support for older versions. The old SDK version is still available for older Node versions.

I have seen some [workarounds](https://stackoverflow.com/a/76026397) to make native `FormData` work with streams. But I am not sure if they have some drawbacks, this needs to be tested.

**Comment by KnorpelSenf** [comment]
I'll try that
